football/urls.py
from django.urls import path

from football.views import (
    index,
    ClubListView,
    ClubCreateView,
    ClubUpdateView,
    ClubDeleteView,
    ClubDetailView,
    CoachListView,
    CoachCreateView,
    CoachUpdateView,
    CoachDeleteView,
    CoachDetailView,
)

urlpatterns = [
    path("", index, name="index"),
    path("home/", index, name="index"),
    path("clubs/", ClubListView.as_view(), name="club-list"),
    path("clubs/create/", ClubCreateView.as_view(), name="club-create"),
    path("clubs/<int:pk>/update/", ClubUpdateView.as_view(), name="club-update"),
    path("clubs/<int:pk>/delete/", ClubDeleteView.as_view(), name="club-delete"),
    path("clubs/<int:pk>/detail/", ClubDetailView.as_view(), name="club-detail"),
    path("coaches/", CoachListView.as_view(), name="coach-list"),
    path("coaches/create/", CoachCreateView.as_view(), name="coach-create"),
    path("coaches/<int:pk>/update/", CoachUpdateView.as_view(), name="coach-update"),
    path("coaches/<int:pk>/delete/", CoachDeleteView.as_view(), name="coach-delete"),
    path("coaches/<int:pk>/detail/", CoachDetailView.as_view(), name="coach-detail"),
]

app_name = "football"

list_printer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("football/", include("football.urls")),
]

football/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime

from django.urls import reverse


class Coach(models.Model):
    first_name = models.CharField(max_length=255, unique=False, blank=False, null=False)
    last_name = models.CharField(max_length=255, unique=False, blank=False, null=False)
    age = models.PositiveIntegerField(
        validators=[
            MinValueValidator(18, message="Coach can't be younger than 18"),
            MaxValueValidator(90, message="Coach can't be older than 90"),
        ],
    )
    nationality = models.CharField(
        max_length=255, unique=False, blank=False, null=False
    )

    class Meta:
        verbose_name_plural = "coaches"

    def get_absolute_url(self):
        return reverse("football:coach-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Club(models.Model):
    coach = models.OneToOneField(
        Coach, related_name="club", on_delete=models.SET_NULL, null=True
    )
    name = models.CharField(max_length=255, unique=False, blank=False, null=False)
    city = models.CharField(max_length=255, unique=False, blank=False, null=False)
    country = models.CharField(max_length=255, unique=False, blank=False, null=False)
    year = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1700, message="Year must be 1700 or greater."),
            MaxValueValidator(
                datetime.datetime.now().year, message="Year cannot be in the future."
            ),
        ],
    )

    class Meta:
        unique_together = ["name", "city"]

    def get_absolute_url(self):
        return reverse("football:club-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.name}  {self.city} - {self.year}"

football/forms.py
from django import forms

from football.models import Club, Coach


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = "__all__"


class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = "__all__"

football/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from football.forms import ClubForm, CoachForm
from football.models import Club, Coach


def index(request):
    """View function for the home page of the site."""

    num_clubs = Club.objects.count()
    num_coaches = Coach.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_clubs": num_clubs,
        "num_coaches": num_coaches,
        "num_visits": num_visits + 1,
    }

    return render(request, "football/index.html", context=context)


class ClubListView(generic.ListView):
    model = Club
    template_name = "football/club_list.html"
    paginate_by = 5
    context_object_name = "clubs_list"


class ClubCreateView(generic.CreateView):
    model = Club
    form_class = ClubForm


class ClubUpdateView(generic.UpdateView):
    model = Club
    form_class = ClubForm


class ClubDetailView(generic.DetailView):
    model = Club


class ClubDeleteView(generic.DeleteView):
    model = Club
    success_url = reverse_lazy("football:club-list")
    template_name = "football/club_confirm_delete.html"


class CoachListView(generic.ListView):
    model = Coach
    template_name = "football/coach_list.html"
    paginate_by = 5
    context_object_name = "coaches_list"


class CoachCreateView(generic.CreateView):
    model = Coach
    form_class = CoachForm


class CoachUpdateView(generic.UpdateView):
    model = Coach
    form_class = CoachForm


class CoachDetailView(generic.DetailView):
    model = Coach


class CoachDeleteView(generic.DeleteView):
    model = Coach
    success_url = reverse_lazy("football:coach-delete")
    template_name = "football/coach_confirm_delete.html"

templates/football/club_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete a club</h1>
  <p>Are you sure that you want to delete club: {{ club.name }}?</p>

  <form action="", method="POST">
  {% csrf_token %}
    <input type="submit", value="Yes, delete" class="btn btn-danger"/>
  </form>


{% endblock %}

templates/football/club_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
  <a style="float: right" class="btn btn-secondary" href="{% url 'football:club-update' pk=club.id %}">Edit</a>
  </h1>
  <p><strong>{{ club.name }}</strong></p>
  <p><strong>This club is from {{ club.city }}</strong></p>
  <p><strong>It's been found at {{ club.year }}</strong></p>
  <p><strong>It's home country is {{ club.country }}</strong></p>
  <p><strong>The head coach of this team is {{ club.coach }}</strong></p>


{% endblock %}

templates/football/club_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} a Club</h1>

  <form action="", method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

    <input class="btm btn-primary" type="submit", value="Submit">
  </form>
{% endblock %}

templates/football/club_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <hr>
  <h1>
    Clubs List
  <a style="float: right" class="btn btn-primary" href="{% url 'football:club-create' %}">Add New Club +</a>
  </h1>
  {% if clubs_list %}
    <table class="table">
    <tr>
      <th>ID</th>
      <th>Club</th>
      <th>City</th>
      <th>Country</th>
      <th>Founded at</th>
      <th>Coach</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for club in clubs_list %}
    <tr>
      <td>
        {{club.id}}
      </td>
      <td>
        <button class="btn btn-link" onclick="window.location='{{ club.get_absolute_url }}';">{{ club.name }}</button>
      </td>
      <td>
        {{ club.city }}
      </td>
      <td>
        {{ club.country }}
      </td>
        <td>
            {{ club.year }}
        </td>
      <td>
        <button class="btn btn-link" onclick="window.location='{{ club.coach.get_absolute_url }}';">{{ club.coach.first_name }} {{ club.coach.last_name }}</button>
      </td>
        <td>
            <a class="btn btn-secondary" href="{% url 'football:club-update' pk=club.id %}">update</a>
        </td>
      <td>
            <a class="btn btn-danger" href="{% url 'football:club-delete' pk=club.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>No clubs, sorry</p>
    {% endif %}

{% endblock %}

templates/football/coach_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete a coach</h1>
  <p>Are you sure that you want to delete {{ coach }}?</p>

  <form action="", method="POST">
  {% csrf_token %}
    <input type="submit", value="Yes, delete" class="btn btn-danger"/>
  </form>


{% endblock %}

templates/football/coach_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
  <a style="float: right" class="btn btn-secondary" href="{% url 'football:coach-update' pk=coach.id %}">Edit</a>
  </h1>
  <p><strong>{{ coach.first_name }} {{ coach.last_name }}</strong></p>
  <p><strong>This coach is from {{ coach.nationality }}</strong></p>
  <p><strong>He is {{ coach.age }} years old</strong></p>
  <p><strong>He is a head coach of {{ coach.club.name }} from {{ coach.club.city }}</strong></p>


{% endblock %}

templates/football/coach_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} a Coach</h1>

  <form action="", method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

    <input class="btm btn-primary" type="submit", value="Submit">
  </form>
{% endblock %}

templates/football/coach_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <hr>
  <h1>
    Coaches List
  <a style="float: right" class="btn btn-primary" href="{% url 'football:coach-create' %}">Add New Coach +</a>
  </h1>
  {% if coaches_list %}
    <table class="table">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Nationality</th>
      <th>Age</th>
      <th>Club</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for coach in coaches_list %}
    <tr>
      <td>
        {{ coach.id }}
      </td>
      <td>
        <button class="btn btn-link" onclick="window.location='{{ coach.get_absolute_url }}';">{{ coach.first_name }} {{ coach.last_name }}</button>
      </td>
      <td>
        {{ coach.nationality }}
      </td>
      <td>
        {{ coach.age }}
      </td>
        <td>
            <button class="btn btn-link" onclick="window.location='{{ coach.club.get_absolute_url }}';">{{ coach.club }}</button>
        </td>
        <td>
          <a class="btn btn-secondary" href="{% url 'football:coach-update' pk=coach.id %}">update</a>
        </td>
      <td>
            <a class="btn btn-danger" href="{% url 'football:coach-delete' pk=coach.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>No coaches, sorry</p>
    {% endif %}

{% endblock %}

templates/football/index.html
{% extends "base.html" %}

{% block content %}

  <div class="jumbotron text-center">
    <h1 class="display-4">Football Service</h1>
    <p class="lead">Discover Football Clubs and Coaches</p>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title">Football Clubs</h5>
            <p class="card-text">Explore our collection of football clubs.</p>
            <strong class="d-block mb-2">At this site, we have {{ num_clubs }} Football Clubs</strong>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title">Coaches</h5>
            <p class="card-text">Meet our experienced football coaches.</p>
            <strong class="d-block mb-2">At this site, we have {{ num_coaches }} Coaches</strong>
          </div>
        </div>
      </div>
    </div>

    <p class="text-center">You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
  </div>
{% endblock %}