football/urls.py
from django.urls import path

from football.views import (
    index,
    ClubListView,
    ClubCreateView,
    ClubUpdateView,
    ClubDeleteView,
    ClubDetailView,
    CoachListView,
    CoachCreateView,
    CoachUpdateView,
    CoachDeleteView,
    CoachDetailView,
)

urlpatterns = [
    path("", index, name="index"),
    path("home/", index, name="index"),
    path("clubs/", ClubListView.as_view(), name="club-list"),
    path("clubs/create/", ClubCreateView.as_view(), name="club-create"),
    path("clubs/<int:pk>/update/", ClubUpdateView.as_view(), name="club-update"),
    path("clubs/<int:pk>/delete/", ClubDeleteView.as_view(), name="club-delete"),
    path("clubs/<int:pk>/detail/", ClubDetailView.as_view(), name="club-detail"),
    path("coaches/", CoachListView.as_view(), name="coach-list"),
    path("coaches/create/", CoachCreateView.as_view(), name="coach-create"),
    path("coaches/<int:pk>/update/", CoachUpdateView.as_view(), name="coach-update"),
    path("coaches/<int:pk>/delete/", CoachDeleteView.as_view(), name="coach-delete"),
    path("coaches/<int:pk>/detail/", CoachDetailView.as_view(), name="coach-detail"),
]

app_name = "football"

list_printer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("football/", include("football.urls")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Football Clubs</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
      <div class="col-sm-2">

      {% block sidebar %}
        {% include "sidebar.html" %}
      {% endblock %}

    </div>

    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/sidebar.html
<ul class="sidebar-nav list-group">
<li class="list-group-item"><a href="{% url 'football:index'%}">Homepage</a></li>
  <br>
  <li class="list-group-item"><a href="{% url 'football:club-list' %}">Football Clubs</a></li>
  <li class="list-group-item"><a href="{% url 'football:coach-list' %}">Coaches</a></li>

</ul>